---
title: "Questions video session 2"
author: "Francesco Minghetti"
date: "4/10/2020"
output:
  md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Question 1: 

**What is the difference between Artifical Intelligence and Augmented Intelligence?**

Artificial Intelligence is a bigger classification and it can be broken down in automated intelligence and augmented intelligence. AI can be defined as Augmented Intelligence squared. Helping business people and the society is called augmented intelligence meanwhile if it helps robots to perform in their tasks, it's called automated intelligence and they are one of the two branches in AI. Augmented Intelligence will make you save time and augment your set of infomation, helping you on unstucted data and also filter. 

## Question 2: 

**Why is Deep Learning such a paradigm shift?**

a

### Question 3:

**What is at stake with (or the lack thereof) digital transformation?**

Global Competitiveness and the future of firms will be put on stake, since every industrial revolution could be the elevator stair for many firms to enlarge themselfes. This means also that there could be winners either losers which will be the firms who don't adapt to the future innovation. 

[Reference to Accenture-WHO document](https://www.accenture.com/t00010101t000000z__w__/ru-ru/_acnmedia/accenture/conversion-assets/dotcom/documents/local/ru-ru/pdf/accenture-digital-transformation.pdf)

#### Question 4:

**Do you think developping countries will leapfrog?**

Surely leapfrogging for many developing countries would be ideal but the main concern is that many developing countries still have a lot of problems regarding accessing internet or even electricity, for example India and Brazil. On the other end China, which is still considered a developing country, is spending a lot of money on research on AI making them a major key player in the world. This leapfrog may happen in the case if the previous problems are resolved and actually the only actionable plan that could work is the chinese one since their economical firepower is immense and they started the process of digitalization and AI research more than 10 years ago.

[Reference to UN article on topic](https://www.un.org/development/desa/en/news/policy/opportunity-for-leapfrogging.html)